package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'CrossVersionTests'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("CrossVersionTests")
    name = "Cross Version Tests"
    description = "Testing the plugin across multiple gradle versions"

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        gradle {
            tasks = "clean testAll"
            buildFile = ""
            jdkHome = "%env.JDK_18%"
        }
    }

    dependencies {
        snapshot(RelativeId("Build")) {
            onDependencyFailure = FailureAction.CANCEL
            onDependencyCancel = FailureAction.CANCEL
        }
    }

    requirements {
        contains("teamcity.agent.jvm.os.name", "Linux")
    }
}))

