package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'TestRetryPluginPublishing'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("TestRetryPluginPublishing")) {
    params {
        add {
            password("SNAPSHOT_REPO_PASSWORD", "credentialsJSON:ce6ba3e6-0b5a-4cce-ad24-09424004567b", display = ParameterDisplay.HIDDEN)
        }
    }
}
