name: Prepare Build Environment
description: Installs required JDKs for building and testing
runs:
  using: "composite"
  steps:

  - name: 'Set up JDK 17'
    uses: actions/setup-java@v4
    with:
      distribution: 'temurin'
      java-version: 17

  - name: Prepare JDK17 env var
    shell: bash
    run: echo "JDK17=$JAVA_HOME" >> $GITHUB_ENV

  - name: Setup Git user
    shell: bash
    run: |
      git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
      git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
